In [1]:
import pandas as pd 
from os import path
import numpy as np 

In [2]:
votes_filepath = "data/1976-2020-president.csv"
electoral_college_filepath = "data/electoral_votes.csv"

data_total = pd.read_csv(votes_filepath)
data_electoral = pd.read_csv(electoral_college_filepath)
data_total.tail(5)


year    state state_po  state_fips  state_cen  state_ic        office  \
4282  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4283  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4284  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4285  2020  WYOMING       WY          56         83        68  US PRESIDENT   
4286  2020  WYOMING       WY          56         83        68  US PRESIDENT   

          candidate party_detailed writein  candidatevotes  totalvotes  \
4282  JORGENSEN, JO    LIBERTARIAN   False            5768      278503   
4283  PIERCE, BROCK    INDEPENDENT   False            2208      278503   
4284            NaN            NaN    True            1739      278503   
4285      OVERVOTES            NaN   False             279      278503   
4286     UNDERVOTES            NaN   False            1459      278503   

       version  notes party_simplified  
4282  20210113    NaN      LIBERTARIAN  
4283  20210113    NaN            OTHER  
4284  20210113    NaN            OTHER  
4285  20210113    NaN            OTHER  
4286  20210113    NaN            OTHER

In [15]:
def expand_electoral_year(text):
    if ('-' in text): 
        start,end = text.strip().split('-')
    else: 
        start = int(text.strip())
        end = start + 1
    return [ year for year in range(int(start), int(end) +1) if year % 4 ==0] 

def process_electoral_data(electoral_data): 
    electoral_temp = electoral_data.copy()
    electoral_temp['state'] = electoral_temp['state'].apply(lambda x:x.lower())
    electoral_temp = (
            electoral_temp
            # .set_index('state_name')
            .melt(id_vars=['state'])
            .rename(columns={'variable':'year'})
        )
    electoral_temp['year'] = electoral_temp['year'].apply(expand_electoral_year)
    # modify district of columbia 
    return electoral_temp.explode(column='year').pivot(index='state',columns='year',values='value')

def get_data_for_year(votes_data,electoral_ata, year,drop_under=0.05):
    # process data for a given year, selecting just major candidates, and dropping unimportant columns 
    # input checking: ensure that the year is usable 
    if year %4 != 0: 
        print(f"invalid year: {year} is not divisible by 4") 
        return None 
    # select year 
    year_data = (votes_data[votes_data.year == year]
                 .copy()
                 .rename(columns={
                     'candidatevotes':'votes', 
                     'party_simplified':'party'
                 })
                )
    year_data['state'] = year_data['state'].apply(lambda x:x.lower())

    # drop candidates whose votes are less than 10% of votes 
    votes_by_cand =(
            year_data
            .groupby("candidate")
            .agg({"votes":sum, "party":"first","office":"first"} )
            .reset_index()
    )
    total_votes = sum(votes_by_cand.votes)
    candidates = votes_by_cand.loc[votes_by_cand.votes >= total_votes*drop_under,'candidate']
    year_data = year_data[year_data.candidate.isin(set(candidates.to_list()))]
    year_data = year_data.drop_duplicates(subset=['state','candidate'],keep='first')
    keep = ['state','candidate','party','votes','electoral_votes']
    # tack on electoral votes
    electoral_data_year = pd.DataFrame(electoral_data[year]).rename(columns={year:'electoral_votes'})
                                            
    year_data = year_data.merge(on='state',right=electoral_data_year)
    
    return year_data[keep].copy()

def tabulate_votes(data, count_function, out_feild): 
    states = list(data.state.unique())
    for state in states: 
        print(state)
        display(data[data.state == state])
        state_votes = data[data.state == state]['electoral_votes'].iloc[0]
        data.loc[data.state == state, out_feild] = count_function(list(data[data.state == state]['votes']),state_votes)
    return data

In [4]:
#preprocess data from electoral college 
electoral_data = process_electoral_data(data_electoral)
# select data from year, and process 
year_data = get_data_for_year(data_total,electoral_data,1992)
# display 
year_data

/Users/zachary/miniconda3/lib/python3.10/site-packages/pandas/core/algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)


state          candidate       party   votes  electoral_votes
0      alabama  BUSH, GEORGE H.W.  REPUBLICAN  804283              9.0
1      alabama      CLINTON, BILL    DEMOCRAT  690080              9.0
2      alabama        PEROT, ROSS       OTHER  183109              9.0
3       alaska  BUSH, GEORGE H.W.  REPUBLICAN  102000              3.0
4       alaska      CLINTON, BILL    DEMOCRAT   78294              3.0
..         ...                ...         ...     ...              ...
148  wisconsin  BUSH, GEORGE H.W.  REPUBLICAN  930855             11.0
149  wisconsin        PEROT, ROSS       OTHER  544479             11.0
150    wyoming  BUSH, GEORGE H.W.  REPUBLICAN   79347              3.0
151    wyoming      CLINTON, BILL    DEMOCRAT   68160              3.0
152    wyoming        PEROT, ROSS       OTHER   51263              3.0

[153 rows x 5 columns]

In [32]:
# define user-function for calculating votes: 
#     follow the following format: 
#      func( [list of vote totals], number of votes) -> [list of electoral votes] 

# First: current system 
def winner_takes_all(vote_totals,electoral_votes):
    # candidate who wins state gets all the votes 
    
    # make everyone have 0
    result = [0]*len(vote_totals)
    # find the guy who won and give him all the votes
    result[np.argmax(vote_totals)] = electoral_votes
    return result

assert(winner_takes_all([13,22,10,17],5) == [0,5,0,0])

# Congressional district method (not doing) 
# Proportional 
def parlimentary_style(vote_totals,electoral_seats):
    # null out votes until everyone is able to get at least one. 
    valid = False 
    while not valid: 
        # find the threshold at one vote more than total votes / electoral seats
        total_votes = sum(vote_totals)
        threshold = total_votes//electoral_seats+1
        print(vote_totals, threshold, valid,min(vote_totals,key = lambda x: x if x !=0 else float('inf')),min(vote_totals,key = lambda x: x if x !=0 else float('inf')) < threshold )

        if min(vote_totals,key = lambda x: x if x !=0 else float('inf')) < threshold: 
            # null out the loser's votes
            print(np.where(np.array(vote_totals)!=0, vote_totals, total_votes))
            print(np.array(vote_totals)!=0)
            vote_totals[np.argmin(np.where(np.array(vote_totals)!=0, vote_totals, total_votes))] = 0
        else: 
            valid = True 
    vote_totals = np.array(vote_totals)
    # now we've nulled out everyone who didn't meet the minimum threshold. 
    raw_electorates = (vote_totals/total_votes)*electoral_seats 
    # take whatever's after the decimal point 
    results = np.floor(raw_electorates)
    # If we need to split up a vote, give it to the person that won the greatest portion of the vote
    if (left_overs := int(electoral_seats - sum(results))) !=0: 
        decimals = list(raw_electorates%1)
        for _ in range(left_overs): 
            last_vote_winner = np.argmax(decimals)
            decimals[last_vote_winner] = 0 
            results[last_vote_winner] +=1 
    return [int(res) for res in results]

assert(parlimentary_style([181, 480, 339,39],10) == [2,5,3,0])
print(parlimentary_style([181, 480, 339,39],10))


[181, 480, 339, 39] 104 False 39 True
[181 480 339  39]
[ True  True  True  True]
[181, 480, 339, 0] 101 False 181 False
[181, 480, 339, 39] 104 False 39 True
[181 480 339  39]
[ True  True  True  True]
[181, 480, 339, 0] 101 False 181 False
[2, 5, 3, 0]


In [34]:
parlimentary_style([192619,20698,9681],3)

[192619, 20698, 9681] 74333 False 9681 True
[192619  20698   9681]
[ True  True  True]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317]
[ True  True False]
[192619, 20698, 0] 71106 False 20698 True
[192619  20698 213317

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [16]:
out = tabulate_votes(year_data,winner_takes_all,'wta_votes')
out = tabulate_votes(year_data,parlimentary_style,'parl_votes')
out.groupby('candidate').agg({'electoral_votes':'sum','wta_votes':'sum','parl_votes':'sum'})

alabama


state          candidate       party   votes  electoral_votes  wta_votes  \
0  alabama  BUSH, GEORGE H.W.  REPUBLICAN  804283              9.0        9.0   
1  alabama      CLINTON, BILL    DEMOCRAT  690080              9.0        0.0   
2  alabama        PEROT, ROSS       OTHER  183109              9.0        0.0   

   parl_votes  
0         5.0  
1         4.0  
2         0.0

alaska


state          candidate       party   votes  electoral_votes  wta_votes  \
3  alaska  BUSH, GEORGE H.W.  REPUBLICAN  102000              3.0        3.0   
4  alaska      CLINTON, BILL    DEMOCRAT   78294              3.0        0.0   
5  alaska        PEROT, ROSS       OTHER   73481              3.0        0.0   

   parl_votes  
3         2.0  
4         1.0  
5         0.0

arizona


state          candidate       party   votes  electoral_votes  wta_votes  \
6  arizona  BUSH, GEORGE H.W.  REPUBLICAN  572086              8.0        8.0   
7  arizona      CLINTON, BILL    DEMOCRAT  543050              8.0        0.0   
8  arizona        PEROT, ROSS       OTHER  353741              8.0        0.0   

   parl_votes  
6         3.0  
7         3.0  
8         2.0

arkansas


state          candidate       party   votes  electoral_votes  \
9   arkansas      CLINTON, BILL    DEMOCRAT  505823              6.0   
10  arkansas  BUSH, GEORGE H.W.  REPUBLICAN  337324              6.0   
11  arkansas        PEROT, ROSS       OTHER   99132              6.0   

    wta_votes  parl_votes  
9         6.0         4.0  
10        0.0         2.0  
11        0.0         0.0

california


state          candidate       party    votes  electoral_votes  \
12  california      CLINTON, BILL    DEMOCRAT  5121325             54.0   
13  california  BUSH, GEORGE H.W.  REPUBLICAN  3630574             54.0   
14  california        PEROT, ROSS       OTHER  2296006             54.0   

    wta_votes  parl_votes  
12       54.0        25.0  
13        0.0        18.0  
14        0.0        11.0

colorado


state          candidate       party   votes  electoral_votes  \
15  colorado      CLINTON, BILL    DEMOCRAT  629681              8.0   
16  colorado  BUSH, GEORGE H.W.  REPUBLICAN  562850              8.0   
17  colorado        PEROT, ROSS       OTHER  366010              8.0   

    wta_votes  parl_votes  
15        8.0         3.0  
16        0.0         3.0  
17        0.0         2.0

connecticut


state          candidate       party   votes  electoral_votes  \
18  connecticut      CLINTON, BILL    DEMOCRAT  682318              8.0   
19  connecticut  BUSH, GEORGE H.W.  REPUBLICAN  578313              8.0   
20  connecticut        PEROT, ROSS       OTHER  348771              8.0   

    wta_votes  parl_votes  
18        8.0         3.0  
19        0.0         3.0  
20        0.0         2.0

delaware


state          candidate       party   votes  electoral_votes  \
21  delaware      CLINTON, BILL    DEMOCRAT  126054              3.0   
22  delaware  BUSH, GEORGE H.W.  REPUBLICAN  102313              3.0   
23  delaware        PEROT, ROSS       OTHER   59213              3.0   

    wta_votes  parl_votes  
21        3.0         2.0  
22        0.0         1.0  
23        0.0         0.0

district of columbia


state          candidate       party   votes  \
24  district of columbia      CLINTON, BILL    DEMOCRAT  192619   
25  district of columbia  BUSH, GEORGE H.W.  REPUBLICAN   20698   
26  district of columbia        PEROT, ROSS       OTHER    9681   

    electoral_votes  wta_votes  parl_votes  
24              3.0        3.0         NaN  
25              3.0        0.0         NaN  
26              3.0        0.0         NaN

florida


state          candidate       party    votes  electoral_votes  \
27  florida  BUSH, GEORGE H.W.  REPUBLICAN  2173310             25.0   
28  florida      CLINTON, BILL    DEMOCRAT  2071698             25.0   
29  florida        PEROT, ROSS       OTHER  1053067             25.0   

    wta_votes  parl_votes  
27       25.0         NaN  
28        0.0         NaN  
29        0.0         NaN

georgia


state          candidate       party    votes  electoral_votes  \
30  georgia      CLINTON, BILL    DEMOCRAT  1008966             13.0   
31  georgia  BUSH, GEORGE H.W.  REPUBLICAN   995252             13.0   
32  georgia        PEROT, ROSS       OTHER   309657             13.0   

    wta_votes  parl_votes  
30       13.0         NaN  
31        0.0         NaN  
32        0.0         NaN

hawaii


state          candidate       party   votes  electoral_votes  wta_votes  \
33  hawaii      CLINTON, BILL    DEMOCRAT  179310              4.0        4.0   
34  hawaii  BUSH, GEORGE H.W.  REPUBLICAN  136822              4.0        0.0   
35  hawaii        PEROT, ROSS       OTHER   53003              4.0        0.0   

    parl_votes  
33         NaN  
34         NaN  
35         NaN

idaho


state          candidate       party   votes  electoral_votes  wta_votes  \
36  idaho  BUSH, GEORGE H.W.  REPUBLICAN  202645              4.0        4.0   
37  idaho      CLINTON, BILL    DEMOCRAT  137013              4.0        0.0   
38  idaho        PEROT, ROSS       OTHER  130395              4.0        0.0   

    parl_votes  
36         NaN  
37         NaN  
38         NaN

illinois


state          candidate       party    votes  electoral_votes  \
39  illinois      CLINTON, BILL    DEMOCRAT  2453350             22.0   
40  illinois  BUSH, GEORGE H.W.  REPUBLICAN  1734096             22.0   
41  illinois        PEROT, ROSS       OTHER   840515             22.0   

    wta_votes  parl_votes  
39       22.0         NaN  
40        0.0         NaN  
41        0.0         NaN

indiana


state          candidate       party   votes  electoral_votes  \
42  indiana  BUSH, GEORGE H.W.  REPUBLICAN  989375             12.0   
43  indiana      CLINTON, BILL    DEMOCRAT  848420             12.0   
44  indiana        PEROT, ROSS       OTHER  455934             12.0   

    wta_votes  parl_votes  
42       12.0         NaN  
43        0.0         NaN  
44        0.0         NaN

iowa


state          candidate       party   votes  electoral_votes  wta_votes  \
45  iowa      CLINTON, BILL    DEMOCRAT  586353              7.0        7.0   
46  iowa  BUSH, GEORGE H.W.  REPUBLICAN  504891              7.0        0.0   
47  iowa        PEROT, ROSS       OTHER  253468              7.0        0.0   

    parl_votes  
45         NaN  
46         NaN  
47         NaN

kansas


state          candidate       party   votes  electoral_votes  wta_votes  \
48  kansas  BUSH, GEORGE H.W.  REPUBLICAN  449951              6.0        6.0   
49  kansas      CLINTON, BILL    DEMOCRAT  390434              6.0        0.0   
50  kansas        PEROT, ROSS       OTHER  312358              6.0        0.0   

    parl_votes  
48         NaN  
49         NaN  
50         NaN

kentucky


state          candidate       party   votes  electoral_votes  \
51  kentucky      CLINTON, BILL    DEMOCRAT  665104              8.0   
52  kentucky  BUSH, GEORGE H.W.  REPUBLICAN  617178              8.0   
53  kentucky        PEROT, ROSS       OTHER  203944              8.0   

    wta_votes  parl_votes  
51        8.0         NaN  
52        0.0         NaN  
53        0.0         NaN

louisiana


state          candidate       party   votes  electoral_votes  \
54  louisiana      CLINTON, BILL    DEMOCRAT  815971              9.0   
55  louisiana  BUSH, GEORGE H.W.  REPUBLICAN  733386              9.0   
56  louisiana        PEROT, ROSS       OTHER  211478              9.0   

    wta_votes  parl_votes  
54        9.0         NaN  
55        0.0         NaN  
56        0.0         NaN

maine


state          candidate       party   votes  electoral_votes  wta_votes  \
57  maine      CLINTON, BILL    DEMOCRAT  263420              4.0        4.0   
58  maine        PEROT, ROSS       OTHER  206820              4.0        0.0   
59  maine  BUSH, GEORGE H.W.  REPUBLICAN  206504              4.0        0.0   

    parl_votes  
57         NaN  
58         NaN  
59         NaN

maryland


state          candidate       party   votes  electoral_votes  \
60  maryland      CLINTON, BILL    DEMOCRAT  988571             10.0   
61  maryland  BUSH, GEORGE H.W.  REPUBLICAN  707094             10.0   
62  maryland        PEROT, ROSS       OTHER  281414             10.0   

    wta_votes  parl_votes  
60       10.0         NaN  
61        0.0         NaN  
62        0.0         NaN

massachusetts


state          candidate       party    votes  electoral_votes  \
63  massachusetts      CLINTON, BILL    DEMOCRAT  1318639             12.0   
64  massachusetts  BUSH, GEORGE H.W.  REPUBLICAN   805039             12.0   
65  massachusetts        PEROT, ROSS       OTHER   630731             12.0   

    wta_votes  parl_votes  
63       12.0         NaN  
64        0.0         NaN  
65        0.0         NaN

michigan


state          candidate       party    votes  electoral_votes  \
66  michigan      CLINTON, BILL    DEMOCRAT  1871182             18.0   
67  michigan  BUSH, GEORGE H.W.  REPUBLICAN  1554940             18.0   
68  michigan        PEROT, ROSS       OTHER   824813             18.0   

    wta_votes  parl_votes  
66       18.0         NaN  
67        0.0         NaN  
68        0.0         NaN

minnesota


state          candidate       party    votes  electoral_votes  \
69  minnesota      CLINTON, BILL    DEMOCRAT  1020997             10.0   
70  minnesota  BUSH, GEORGE H.W.  REPUBLICAN   747841             10.0   
71  minnesota        PEROT, ROSS       OTHER   562506             10.0   

    wta_votes  parl_votes  
69       10.0         NaN  
70        0.0         NaN  
71        0.0         NaN

mississippi


state          candidate       party   votes  electoral_votes  \
72  mississippi  BUSH, GEORGE H.W.  REPUBLICAN  487793              7.0   
73  mississippi      CLINTON, BILL    DEMOCRAT  400258              7.0   
74  mississippi        PEROT, ROSS       OTHER   85626              7.0   

    wta_votes  parl_votes  
72        7.0         NaN  
73        0.0         NaN  
74        0.0         NaN

missouri


state          candidate       party    votes  electoral_votes  \
75  missouri      CLINTON, BILL    DEMOCRAT  1053873             11.0   
76  missouri  BUSH, GEORGE H.W.  REPUBLICAN   811159             11.0   
77  missouri        PEROT, ROSS       OTHER   518741             11.0   

    wta_votes  parl_votes  
75       11.0         NaN  
76        0.0         NaN  
77        0.0         NaN

montana


state          candidate       party   votes  electoral_votes  \
78  montana      CLINTON, BILL    DEMOCRAT  154507              3.0   
79  montana  BUSH, GEORGE H.W.  REPUBLICAN  144207              3.0   
80  montana        PEROT, ROSS       OTHER  107225              3.0   

    wta_votes  parl_votes  
78        3.0         NaN  
79        0.0         NaN  
80        0.0         NaN

nebraska


state          candidate       party   votes  electoral_votes  \
81  nebraska  BUSH, GEORGE H.W.  REPUBLICAN  343678              5.0   
82  nebraska      CLINTON, BILL    DEMOCRAT  216864              5.0   
83  nebraska        PEROT, ROSS       OTHER  174104              5.0   

    wta_votes  parl_votes  
81        5.0         NaN  
82        0.0         NaN  
83        0.0         NaN

nevada


state          candidate       party   votes  electoral_votes  wta_votes  \
84  nevada      CLINTON, BILL    DEMOCRAT  189148              4.0        4.0   
85  nevada  BUSH, GEORGE H.W.  REPUBLICAN  175828              4.0        0.0   
86  nevada        PEROT, ROSS       OTHER  132580              4.0        0.0   

    parl_votes  
84         NaN  
85         NaN  
86         NaN

new hampshire


state          candidate       party   votes  electoral_votes  \
87  new hampshire      CLINTON, BILL    DEMOCRAT  209040              4.0   
88  new hampshire  BUSH, GEORGE H.W.  REPUBLICAN  202484              4.0   
89  new hampshire        PEROT, ROSS       OTHER  121337              4.0   

    wta_votes  parl_votes  
87        4.0         NaN  
88        0.0         NaN  
89        0.0         NaN

new jersey


state          candidate       party    votes  electoral_votes  \
90  new jersey      CLINTON, BILL    DEMOCRAT  1436206             15.0   
91  new jersey  BUSH, GEORGE H.W.  REPUBLICAN  1356865             15.0   
92  new jersey        PEROT, ROSS       OTHER   521829             15.0   

    wta_votes  parl_votes  
90       15.0         NaN  
91        0.0         NaN  
92        0.0         NaN

new mexico


state          candidate       party   votes  electoral_votes  \
93  new mexico      CLINTON, BILL    DEMOCRAT  261617              5.0   
94  new mexico  BUSH, GEORGE H.W.  REPUBLICAN  212824              5.0   
95  new mexico        PEROT, ROSS       OTHER   91895              5.0   

    wta_votes  parl_votes  
93        5.0         NaN  
94        0.0         NaN  
95        0.0         NaN

new york


state          candidate       party    votes  electoral_votes  \
96  new york      CLINTON, BILL    DEMOCRAT  3346894             33.0   
97  new york  BUSH, GEORGE H.W.  REPUBLICAN  2041690             33.0   
98  new york        PEROT, ROSS       OTHER  1090721             33.0   

    wta_votes  parl_votes  
96       33.0         NaN  
97        0.0         NaN  
98        0.0         NaN

north carolina


state          candidate       party    votes  electoral_votes  \
99   north carolina  BUSH, GEORGE H.W.  REPUBLICAN  1134661             14.0   
100  north carolina      CLINTON, BILL    DEMOCRAT  1114042             14.0   
101  north carolina        PEROT, ROSS       OTHER   357864             14.0   

     wta_votes  parl_votes  
99        14.0         NaN  
100        0.0         NaN  
101        0.0         NaN

north dakota


state          candidate       party   votes  electoral_votes  \
102  north dakota  BUSH, GEORGE H.W.  REPUBLICAN  136244              3.0   
103  north dakota      CLINTON, BILL    DEMOCRAT   99168              3.0   
104  north dakota        PEROT, ROSS       OTHER   71084              3.0   

     wta_votes  parl_votes  
102        3.0         NaN  
103        0.0         NaN  
104        0.0         NaN

ohio


state          candidate       party    votes  electoral_votes  wta_votes  \
105  ohio      CLINTON, BILL    DEMOCRAT  1984942             21.0       21.0   
106  ohio  BUSH, GEORGE H.W.  REPUBLICAN  1894310             21.0        0.0   
107  ohio        PEROT, ROSS       OTHER  1036426             21.0        0.0   

     parl_votes  
105         NaN  
106         NaN  
107         NaN

oklahoma


state          candidate       party   votes  electoral_votes  \
108  oklahoma  BUSH, GEORGE H.W.  REPUBLICAN  592929              8.0   
109  oklahoma      CLINTON, BILL    DEMOCRAT  473066              8.0   
110  oklahoma        PEROT, ROSS       OTHER  319878              8.0   

     wta_votes  parl_votes  
108        8.0         NaN  
109        0.0         NaN  
110        0.0         NaN

oregon


state          candidate       party   votes  electoral_votes  \
111  oregon      CLINTON, BILL    DEMOCRAT  621314              7.0   
112  oregon  BUSH, GEORGE H.W.  REPUBLICAN  475757              7.0   
113  oregon        PEROT, ROSS       OTHER  354091              7.0   

     wta_votes  parl_votes  
111        7.0         NaN  
112        0.0         NaN  
113        0.0         NaN

pennsylvania


state          candidate       party    votes  electoral_votes  \
114  pennsylvania      CLINTON, BILL    DEMOCRAT  2239164             23.0   
115  pennsylvania  BUSH, GEORGE H.W.  REPUBLICAN  1791841             23.0   
116  pennsylvania        PEROT, ROSS       OTHER   902667             23.0   

     wta_votes  parl_votes  
114       23.0         NaN  
115        0.0         NaN  
116        0.0         NaN

rhode island


state          candidate       party   votes  electoral_votes  \
117  rhode island      CLINTON, BILL    DEMOCRAT  213299              4.0   
118  rhode island  BUSH, GEORGE H.W.  REPUBLICAN  131601              4.0   
119  rhode island        PEROT, ROSS       OTHER  105045              4.0   

     wta_votes  parl_votes  
117        4.0         NaN  
118        0.0         NaN  
119        0.0         NaN

south carolina


state          candidate       party   votes  electoral_votes  \
120  south carolina  BUSH, GEORGE H.W.  REPUBLICAN  577507              8.0   
121  south carolina      CLINTON, BILL    DEMOCRAT  525514              8.0   
122  south carolina        PEROT, ROSS       OTHER  119257              8.0   

     wta_votes  parl_votes  
120        8.0         NaN  
121        0.0         NaN  
122        0.0         NaN

south dakota


state          candidate       party   votes  electoral_votes  \
123  south dakota  BUSH, GEORGE H.W.  REPUBLICAN  136718              3.0   
124  south dakota      CLINTON, BILL    DEMOCRAT  124888              3.0   
125  south dakota        PEROT, ROSS       OTHER   73295              3.0   

     wta_votes  parl_votes  
123        3.0         NaN  
124        0.0         NaN  
125        0.0         NaN

tennessee


state          candidate       party   votes  electoral_votes  \
126  tennessee      CLINTON, BILL    DEMOCRAT  933521             11.0   
127  tennessee  BUSH, GEORGE H.W.  REPUBLICAN  841300             11.0   
128  tennessee        PEROT, ROSS       OTHER  199968             11.0   

     wta_votes  parl_votes  
126       11.0         NaN  
127        0.0         NaN  
128        0.0         NaN

texas


state          candidate       party    votes  electoral_votes  \
129  texas  BUSH, GEORGE H.W.  REPUBLICAN  2496071             32.0   
130  texas      CLINTON, BILL    DEMOCRAT  2281815             32.0   
131  texas        PEROT, ROSS       OTHER  1354781             32.0   

     wta_votes  parl_votes  
129       32.0         NaN  
130        0.0         NaN  
131        0.0         NaN

utah


state          candidate       party   votes  electoral_votes  wta_votes  \
132  utah  BUSH, GEORGE H.W.  REPUBLICAN  322632              5.0        5.0   
133  utah        PEROT, ROSS       OTHER  203400              5.0        0.0   
134  utah      CLINTON, BILL    DEMOCRAT  183429              5.0        0.0   

     parl_votes  
132         NaN  
133         NaN  
134         NaN

vermont


state          candidate       party   votes  electoral_votes  \
135  vermont      CLINTON, BILL    DEMOCRAT  133592              3.0   
136  vermont  BUSH, GEORGE H.W.  REPUBLICAN   88122              3.0   
137  vermont        PEROT, ROSS       OTHER   65991              3.0   

     wta_votes  parl_votes  
135        3.0         NaN  
136        0.0         NaN  
137        0.0         NaN

virginia


state          candidate       party    votes  electoral_votes  \
138  virginia  BUSH, GEORGE H.W.  REPUBLICAN  1150517             13.0   
139  virginia      CLINTON, BILL    DEMOCRAT  1038650             13.0   
140  virginia        PEROT, ROSS       OTHER   348639             13.0   

     wta_votes  parl_votes  
138       13.0         NaN  
139        0.0         NaN  
140        0.0         NaN

washington


state          candidate       party   votes  electoral_votes  \
141  washington      CLINTON, BILL    DEMOCRAT  993037             11.0   
142  washington  BUSH, GEORGE H.W.  REPUBLICAN  731234             11.0   
143  washington        PEROT, ROSS       OTHER  541780             11.0   

     wta_votes  parl_votes  
141       11.0         NaN  
142        0.0         NaN  
143        0.0         NaN

west virginia


state          candidate       party   votes  electoral_votes  \
144  west virginia      CLINTON, BILL    DEMOCRAT  331001              5.0   
145  west virginia  BUSH, GEORGE H.W.  REPUBLICAN  241974              5.0   
146  west virginia        PEROT, ROSS       OTHER  108829              5.0   

     wta_votes  parl_votes  
144        5.0         NaN  
145        0.0         NaN  
146        0.0         NaN

wisconsin


state          candidate       party    votes  electoral_votes  \
147  wisconsin      CLINTON, BILL    DEMOCRAT  1041066             11.0   
148  wisconsin  BUSH, GEORGE H.W.  REPUBLICAN   930855             11.0   
149  wisconsin        PEROT, ROSS       OTHER   544479             11.0   

     wta_votes  parl_votes  
147       11.0         NaN  
148        0.0         NaN  
149        0.0         NaN

wyoming


state          candidate       party  votes  electoral_votes  \
150  wyoming  BUSH, GEORGE H.W.  REPUBLICAN  79347              3.0   
151  wyoming      CLINTON, BILL    DEMOCRAT  68160              3.0   
152  wyoming        PEROT, ROSS       OTHER  51263              3.0   

     wta_votes  parl_votes  
150        3.0         NaN  
151        0.0         NaN  
152        0.0         NaN

alabama


state          candidate       party   votes  electoral_votes  wta_votes  \
0  alabama  BUSH, GEORGE H.W.  REPUBLICAN  804283              9.0        9.0   
1  alabama      CLINTON, BILL    DEMOCRAT  690080              9.0        0.0   
2  alabama        PEROT, ROSS       OTHER  183109              9.0        0.0   

   parl_votes  
0         5.0  
1         4.0  
2         0.0

alaska


state          candidate       party   votes  electoral_votes  wta_votes  \
3  alaska  BUSH, GEORGE H.W.  REPUBLICAN  102000              3.0        3.0   
4  alaska      CLINTON, BILL    DEMOCRAT   78294              3.0        0.0   
5  alaska        PEROT, ROSS       OTHER   73481              3.0        0.0   

   parl_votes  
3         2.0  
4         1.0  
5         0.0

arizona


state          candidate       party   votes  electoral_votes  wta_votes  \
6  arizona  BUSH, GEORGE H.W.  REPUBLICAN  572086              8.0        8.0   
7  arizona      CLINTON, BILL    DEMOCRAT  543050              8.0        0.0   
8  arizona        PEROT, ROSS       OTHER  353741              8.0        0.0   

   parl_votes  
6         3.0  
7         3.0  
8         2.0

arkansas


state          candidate       party   votes  electoral_votes  \
9   arkansas      CLINTON, BILL    DEMOCRAT  505823              6.0   
10  arkansas  BUSH, GEORGE H.W.  REPUBLICAN  337324              6.0   
11  arkansas        PEROT, ROSS       OTHER   99132              6.0   

    wta_votes  parl_votes  
9         6.0         4.0  
10        0.0         2.0  
11        0.0         0.0

california


state          candidate       party    votes  electoral_votes  \
12  california      CLINTON, BILL    DEMOCRAT  5121325             54.0   
13  california  BUSH, GEORGE H.W.  REPUBLICAN  3630574             54.0   
14  california        PEROT, ROSS       OTHER  2296006             54.0   

    wta_votes  parl_votes  
12       54.0        25.0  
13        0.0        18.0  
14        0.0        11.0

colorado


state          candidate       party   votes  electoral_votes  \
15  colorado      CLINTON, BILL    DEMOCRAT  629681              8.0   
16  colorado  BUSH, GEORGE H.W.  REPUBLICAN  562850              8.0   
17  colorado        PEROT, ROSS       OTHER  366010              8.0   

    wta_votes  parl_votes  
15        8.0         3.0  
16        0.0         3.0  
17        0.0         2.0

connecticut


state          candidate       party   votes  electoral_votes  \
18  connecticut      CLINTON, BILL    DEMOCRAT  682318              8.0   
19  connecticut  BUSH, GEORGE H.W.  REPUBLICAN  578313              8.0   
20  connecticut        PEROT, ROSS       OTHER  348771              8.0   

    wta_votes  parl_votes  
18        8.0         3.0  
19        0.0         3.0  
20        0.0         2.0

delaware


state          candidate       party   votes  electoral_votes  \
21  delaware      CLINTON, BILL    DEMOCRAT  126054              3.0   
22  delaware  BUSH, GEORGE H.W.  REPUBLICAN  102313              3.0   
23  delaware        PEROT, ROSS       OTHER   59213              3.0   

    wta_votes  parl_votes  
21        3.0         2.0  
22        0.0         1.0  
23        0.0         0.0

district of columbia


state          candidate       party   votes  \
24  district of columbia      CLINTON, BILL    DEMOCRAT  192619   
25  district of columbia  BUSH, GEORGE H.W.  REPUBLICAN   20698   
26  district of columbia        PEROT, ROSS       OTHER    9681   

    electoral_votes  wta_votes  parl_votes  
24              3.0        3.0         NaN  
25              3.0        0.0         NaN  
26              3.0        0.0         NaN

KeyboardInterrupt: 